---
- name: Connect to GCP VM
  hosts: all
  vars:
    vault_service_account_content: "{{ lookup('file', 'service_account.json') }}"
  tasks:
    - name: SSH into GCP VM
      gcp_compute_ssh:
        project: your_project_id
        auth_kind: serviceaccount
        service_account_file: "{{ vault_service_account_content }}"
    - name: pinging servers.
      ping:    